/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentrecordsystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;


/**
 *
 * @author user
 */
public class SystemRecordSystem extends javax.swing.JFrame
{
    Connection  conn = null;
    ResultSet rs = null;
    PreparedStatement pst=null;
    /**
     * Creates new form SystemRecordSystem
     */
    public SystemRecordSystem()
    {
        initComponents();
        conn = DBConnect.ConnecrDb();
        UpdateJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        regNumTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fNameTF = new javax.swing.JTextField();
        lNameTF = new javax.swing.JTextField();
        deptTF = new javax.swing.JTextField();
        genderCB = new javax.swing.JComboBox<>();
        stateCB = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        recordTB = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        searchTF = new javax.swing.JTextField();
        searchBT = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        deleteBT = new javax.swing.JButton();
        insertBT = new javax.swing.JButton();
        exitBT = new javax.swing.JButton();
        updateBT = new javax.swing.JButton();
        resetBT = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(59, 131, 113));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(719, 662));
        jDesktopPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDesktopPane1MouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        regNumTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        regNumTF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        regNumTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regNumTFActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("REGISTRATION NUMBER");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("FIRST NAME :");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("LAST NAME :");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("DEPARTMENT :");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("STATE :");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("GENDER :");
        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        fNameTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        fNameTF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        fNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameTFActionPerformed(evt);
            }
        });

        lNameTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lNameTF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameTFActionPerformed(evt);
            }
        });

        deptTF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        deptTF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        deptTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptTFActionPerformed(evt);
            }
        });

        genderCB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        genderCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT GENDER", "MALE", "FEMALE" }));

        stateCB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        stateCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT STATE ", "Abia", "Adamawa", "Akwa-ibom", "Anambra", "Bauchi", "Bayelsa", "Benue", "Borno", "Cross River", "Delta", "Ebonyi", "Edo", "Ekiti", "Enugu", "Gombe", "Imo", "Jigawa", "Kaduna", "Kastina", "Kano", "Kebbi", "Kogi", "Kwara", "Lagos", "Nassarawa", "Niger", "Ogun", "Ondo", "Osun", "Oyo", "Plateau", "River", "Sokoto", "Taraba", "Yobe", "Zamfara", "F.C.T", " ", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(stateCB, 0, 238, Short.MAX_VALUE)
                                .addGap(3, 3, 3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lNameTF)
                                    .addComponent(genderCB, 0, 238, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deptTF, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fNameTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genderCB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateCB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deptTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("STUDENT MANAGEMENT SYSTEM");

        recordTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        recordTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recordTBMouseClicked(evt);
            }
        });
        recordTB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                recordTBKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                recordTBKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(recordTB);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        searchTF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        searchTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTFActionPerformed(evt);
            }
        });

        searchBT.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        searchBT.setText("SEARCH");
        searchBT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        searchBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchTF, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(searchBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        deleteBT.setBackground(new java.awt.Color(78, 130, 160));
        deleteBT.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        deleteBT.setText("DELETE");
        deleteBT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        deleteBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTActionPerformed(evt);
            }
        });

        insertBT.setBackground(new java.awt.Color(78, 130, 160));
        insertBT.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        insertBT.setText("INSERT");
        insertBT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        insertBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBTActionPerformed(evt);
            }
        });

        exitBT.setBackground(new java.awt.Color(255, 0, 51));
        exitBT.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        exitBT.setText("EXIT");
        exitBT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        exitBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTActionPerformed(evt);
            }
        });

        updateBT.setBackground(new java.awt.Color(78, 130, 160));
        updateBT.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        updateBT.setText("UPDATE");
        updateBT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        updateBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBTActionPerformed(evt);
            }
        });

        resetBT.setBackground(new java.awt.Color(78, 130, 160));
        resetBT.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        resetBT.setText("RESET");
        resetBT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        resetBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateBT, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(deleteBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insertBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resetBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(insertBT, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateBT, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteBT, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resetBT, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitBT, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(171, 171, 171))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void  UpdateJTable()
    {
    
        String sql = "Select  * from StudentTable ";
        
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            // LINE OF CODE TO CONNECT JTABLE TO THE DATABASE
            recordTB.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, e);
        }
        finally
        {
            try {
                
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
    
         }
       }
    private void regNumTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regNumTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regNumTFActionPerformed

    private void fNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameTFActionPerformed

    private void lNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameTFActionPerformed

    private void deptTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptTFActionPerformed

    private void searchTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTFActionPerformed

    private void searchBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTActionPerformed
        // TODO add your handling code here:
        try
        {
          String sql = "select * from StudentTable where Registration_Number=?";
          pst = conn.prepareStatement(sql);
          pst.setString(1, searchTF.getText());
          
          rs = pst.executeQuery();
          // pst.execute();
          if(rs.next())
          {
           String add1 = rs.getString("Registration_Number");
           regNumTF.setText(add1);
           String add2 = rs.getString("First_Name");
           fNameTF.setText(add2);
           String add3 = rs.getString("Last_Name");
           lNameTF.setText(add3);
           String add4 = rs.getString("Gender");
           genderCB.setSelectedItem(add4);
           String add5 = rs.getString("State");
           stateCB.setSelectedItem(add5);
           String add6 = rs.getString("Department");
           deptTF.setText(add6);
           
           UpdateJTable();
           
          }
        } catch (Exception e) // or (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
            //Logger.getLogger(SystemRecordSystem.class.getName()).log(Level.SEVERE, null, ex);
        }finally
        {
            try 
            {
               rs.close();
               pst.close();
               //conn.close());
            } catch (Exception e) {
            }
        }
        //=================================UPDATEJTable=============================
        
        //==============================================SEARCH BY FIRST_NAME=========================================================================
                        try
        {
          String sql = "select * from StudentTable where First_Name=?";
          pst = conn.prepareStatement(sql);
          pst.setString(1, searchTF.getText());
          
          rs = pst.executeQuery();
          // pst.execute();
          if(rs.next())
          {
           String add1 = rs.getString("Registration_Number");
           regNumTF.setText(add1);
           String add2 = rs.getString("First_Name");
           fNameTF.setText(add2);
           String add3 = rs.getString("Last_Name");
           lNameTF.setText(add3);
           String add4 = rs.getString("Gender");
           genderCB.setSelectedItem(add4);
           String add5 = rs.getString("State");
           stateCB.setSelectedItem(add5);
           String add6 = rs.getString("Department");
           deptTF.setText(add6);
           
           UpdateJTable();
           
          }
        } catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, e);
            //Logger.getLogger(SystemRecordSystem.class.getName()).log(Level.SEVERE, null, ex);
        }finally
        {
            try 
            {
               rs.close();
               pst.close();
               //conn.close());
            } catch (Exception e) {
            }
        }
      //=========================SEARCH BY LAST_NAME=================================================================
                 try
        {
          String sql = "select * from StudentTable where Last_Name=?";
          pst = conn.prepareStatement(sql);
          pst.setString(1, searchTF.getText());
          
          rs = pst.executeQuery();
          // pst.execute();
          if(rs.next())
          {
           String add1 = rs.getString("Registration_Number");
           regNumTF.setText(add1);
           String add2 = rs.getString("First_Name");
           fNameTF.setText(add2);
           String add3 = rs.getString("Last_Name");
           lNameTF.setText(add3);
           String add4 = rs.getString("Gender");
           genderCB.setSelectedItem(add4);
           String add5 = rs.getString("State");
           stateCB.setSelectedItem(add5);
           String add6 = rs.getString("Department");
           deptTF.setText(add6);
           
           UpdateJTable();
           
          }
        } catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, e);
            //Logger.getLogger(SystemRecordSystem.class.getName()).log(Level.SEVERE, null, ex);
        }finally
        {
            try 
            {
               rs.close();
               pst.close();
               //conn.close());
            } catch (Exception e) {
            }
        }
      //=============================SERACH BY DEPARTMENT===================
              try
        {
          String sql = "select * from StudentTable where Department=?";
          pst = conn.prepareStatement(sql);
          pst.setString(1, searchTF.getSelectedText());
          
          rs = pst.executeQuery();
          // pst.execute();
          if(rs.next())
          {
           String add1 = rs.getString("Registration_Number");
           regNumTF.setText(add1);
           String add2 = rs.getString("First_Name");
           fNameTF.setText(add2);
           String add3 = rs.getString("Last_Name");
           lNameTF.setText(add3);
           String add4 = rs.getString("Gender");
           genderCB.setSelectedItem(add4);
           String add5 = rs.getString("State");
           stateCB.setSelectedItem(add5);
           String add6 = rs.getString("Department");
           deptTF.setText(add6);
           
           UpdateJTable();
           
          }
        } catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, e);
            //Logger.getLogger(SystemRecordSystem.class.getName()).log(Level.SEVERE, null, ex);
        }finally
        {
            try 
            {
               rs.close();
               pst.close();
               //conn.close());
            } catch (Exception e) {
            }
        }
      

 
    }//GEN-LAST:event_searchBTActionPerformed

    private void deleteBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTActionPerformed
        // TODO add your handling code here:
        // CODE TO DELETE A RECORD FROM THE DATABASE 
        int promptYesNo = JOptionPane.showConfirmDialog(null, "Do you really want to delete", "Delete Record?", JOptionPane.YES_NO_OPTION);
        
        if (promptYesNo ==0 )
        {
            try
            {
             String sql = "delete from StudentTable where Registration_Number=?"; 
             pst = conn.prepareStatement(sql);
             
             pst.setString(1, regNumTF.getText());
             
             pst.execute();
             JOptionPane.showMessageDialog(null, "Deleted");
             
            } catch (Exception e) 
            {
                JOptionPane.showMessageDialog(null, e);
            }
            
            UpdateJTable();
        }
    }//GEN-LAST:event_deleteBTActionPerformed

    private void insertBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBTActionPerformed
        // TODO add your handling code here:
        // A CODE TO INSERT RECORD INTO THE DATABASE
        String sql ="INSERT INTO StudentTable (Registration_Number,First_Name,Last_Name,Gender,State,Department) values(?,?,?,?,?,?)";
            try
            {
            pst = conn.prepareStatement(sql);
             pst.setString(1, regNumTF.getText());
             pst.setString(2, fNameTF.getText());
             pst.setString(3, lNameTF.getText());
             pst.setString(4, genderCB.getSelectedItem().toString());
             pst.setString(5, stateCB.getSelectedItem().toString());
             pst.setString(6, deptTF.getText());
             
             pst.execute();
             
             JOptionPane.showMessageDialog(null, "INSERTED");
             UpdateJTable();
              
            
        } catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, e);
        }finally
            {
                try {
                    rs.close();
                    pst.close();
                } catch (Exception e) {
                }
            }
    }//GEN-LAST:event_insertBTActionPerformed

    private void exitBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBTActionPerformed

    private void updateBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBTActionPerformed
        // TODO add your handling code here:
        try 
        {
           String value1 = regNumTF.getText();
           String value2 = fNameTF.getText();
           String value3 = lNameTF.getText();
           String value4 = genderCB.getSelectedItem().toString();
           String value5 = stateCB.getSelectedItem().toString();
           String value6 = deptTF.getText();
           
           String sql = "update StudentTable set First_Name='" + value2 + "', Last_Name='" + value3 + "', Gender='" + value4 + "', State='" + value5 + "', Department='" + value6 + "' where Registration_Number='" + value1 +"'";
           pst = conn.prepareStatement(sql);
           pst.execute();
           UpdateJTable();
           JOptionPane.showMessageDialog(null, "Updated");
           
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        finally 
        {
            try
            {
                rs.close();
                pst.close();
            } catch (Exception e)
            {
                
            }
        }
    }//GEN-LAST:event_updateBTActionPerformed

    private void resetBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBTActionPerformed
        // CODE TO RESET THE FIELDS AND COMBOS :
       
        
        regNumTF.setText(null);
        fNameTF.setText(null);
        lNameTF.setText(null);
        genderCB.setSelectedItem("SELECT GENDER");
        stateCB.setSelectedItem("SELECT STATE ");
        deptTF.setText(null);
        searchTF.setText(null);
    }//GEN-LAST:event_resetBTActionPerformed

    private void jDesktopPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDesktopPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jDesktopPane1MouseClicked

    private void recordTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recordTBMouseClicked
        // TODO add your handling code here:
         
    }//GEN-LAST:event_recordTBMouseClicked

    private void recordTBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_recordTBKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_recordTBKeyPressed

    private void recordTBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_recordTBKeyReleased
        // TODO add your handling code here:
         int row = recordTB.getSelectedRow();
         regNumTF.setText(recordTB.getModel().getValueAt( row,0).toString());
         fNameTF.setText(recordTB.getModel().getValueAt( row,1).toString());
         lNameTF.setText(recordTB.getModel().getValueAt(row,2).toString());
         genderCB.setSelectedItem(recordTB.getModel().getValueAt( row,3).toString());
         stateCB.setSelectedItem(recordTB.getModel().getValueAt( row,4).toString());
         deptTF.setText(recordTB.getModel().getValueAt( row,5).toString());

    }//GEN-LAST:event_recordTBKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemRecordSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemRecordSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemRecordSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemRecordSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemRecordSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBT;
    private javax.swing.JTextField deptTF;
    private javax.swing.JButton exitBT;
    private javax.swing.JTextField fNameTF;
    private javax.swing.JComboBox<String> genderCB;
    private javax.swing.JButton insertBT;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField lNameTF;
    private javax.swing.JTable recordTB;
    private javax.swing.JTextField regNumTF;
    private javax.swing.JButton resetBT;
    private javax.swing.JButton searchBT;
    private javax.swing.JTextField searchTF;
    private javax.swing.JComboBox<String> stateCB;
    private javax.swing.JButton updateBT;
    // End of variables declaration//GEN-END:variables

    private static class DbUtils
    {

        private static TableModel resultSetToTableModel(ResultSet rs)
        {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public DbUtils()
        {
        }
    }
}
